baseurl = "https://robsontech.au/"
theme = "casper-two"
languageCode = "en-AU"
disqusShortname = ""
paginate = 6
#SectionPagesMenu = "main"

[params]
title = "A seasoned programmer"
subtitle = "I got a head full of ideas that are drivin' me insane."

cover = "images/header.jpg"
description = "This is my first Hugo website."
metaDescription = ""
googleAnalytics = ""
customCSS = []
RSSLink = ""

twitterName = "alanrob17"
fbName = ""
githubName = "alanrob17"

logo = ""
orgName = "Alan Robson"
orgWebsite = "https://www.robsonmail.com"
orgDescription = "This is Software Inc."

author = "AR"
authorAvatar = "images/ghost-icon.png"
authorLocation = "Melbourne, VIC"
authorWebsite = "https://robsonmail.com"
authorDescription = "Developer"

pageNotFoundTitle = "404 - Page not found"

#casper or caspertwo
singleViewStyle = "casper"

pygmentsUseClasses = true

[permalinks]
post = "/:slug/"

[[menu.main]]
name = "Home"
url = "/post"
weight = 200

[[menu.main]]
name = "Programming"
url = "/categories/programming/"
weight = 100

[[menu.main]]
name = "Music"
url = "/categories/music/"
weight = 99


[[menu.main]]
name = "RecordDB"
url = "https://recordlist.netlify.app/"
weight = 95
